function position = initialize_ic_grid(strainlineResolution,flowDomain)
%initialize_ic_grid Initialize initial conditions on cartesian grid.

deltaX = (flowDomain(1,2) - flowDomain(1,1))...
    /(double(strainlineResolution(1)) + 1);
deltaY = (flowDomain(2,2) - flowDomain(2,1))...
    /(double(strainlineResolution(2)) + 1);
[positionX positionY] = meshgrid(...
    flowDomain(1,1) + deltaX:deltaX:flowDomain(1,2) - deltaX,...
    flowDomain(2,1) + deltaY:deltaY:flowDomain(2,2) - deltaY);
position(:,1) = reshape(positionX,numel(positionX),1);
position(:,2) = reshape(positionY,numel(positionY),1);
