% Remove all calculated fields of a strainline structure.

function strainline = reset_strainline(strainline)

fieldsToDelete = {...
    'filteredSegmentIndex',...
    'geodesicDeviation',...
    'initialPosition',...
    'position',...
    'relativeStretching',...
    'hausdorffDistance',...
    'segmentIndex'};

for iField = 1:length(fieldsToDelete)
    if isfield(strainline,fieldsToDelete{iField})
        strainline = rmfield(strainline,fieldsToDelete{iField});
    end
end