function a1 = setup_figure(flowDomain)

figure
a1 = axes;
set(a1,'nextplot','add',...
    'box','on',...
    'DataAspectRatio',[1 1 1],...
    'DataAspectRatioMode','Manual',...
    'XGrid','on',...
    'YGrid','on',...
    'XLim',flowDomain(1,:),...
    'YLim',flowDomain(2,:))
xlabel(a1,'x')
ylabel(a1,'y')