function input = shear_lcs_script(input)

input.flow = set_flow_default(input.flow);

[input.flow,input.shearline] = compute_shear_lcs(input.flow,...
    input.shearline);

mainAxes = setup_figure(input.flow);

showPlot = struct('shearlinePosFiltered',true,...
                  'shearlineNegFiltered',true,...
                  'shearlinePosClosed',true,...
                  'shearlineNegClosed',true);

plot_shear_lcs(mainAxes,input.flow,input.shearline,showPlot)

function a1 = setup_figure(flow)

figure
a1 = axes;
set(a1,'nextplot','add',...
    'box','on',...
    'DataAspectRatio',[1 1 1],...
    'DataAspectRatioMode','Manual',...
    'XGrid','on',...
    'YGrid','on',...
    'XLim',flow.domain(1,:),...
    'YLim',flow.domain(2,:))
xlabel(a1,'x')
ylabel(a1,'y')
