userHome = getenv('HOME');

mex('-v','-largeArrayDims','CC=gcc-4.4','CXXFLAGS=\$CFLAGS -fopenmp',...
    'LDFLAGS=\$LDFLAGS -fopenmp','-lgsl','-lgslcblas',...
    'compute_closed_shearline.cpp','RegularGrid.cpp')
